### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by AngeloGiacco** [kartiknair/TypeMD#1]
hi there, 

I am following your tutorial on the dev community. it was really informative. I am new to react so I'm simply trying to implement this website locally for myself. When i am comfortable with react I will try to expand on it. 

Currently it will not compile. I get this error:

![Screenshot 2020-05-14 at 23 09 44](https://user-images.githubusercontent.com/29235343/81990908-0128af80-9638-11ea-902f-0b5611f696f1.png)

Do you know how i can resolve this? 

Thanks for your tutorial and any help!

**Comment by kartiknair** [comment]
Hey there, this issue is being caused because when I created this project since I knew I was going to write a blog post about it I created a `jsconfig.json` file that sets the base URL to the `src` directory. This gives us more readable import paths.

So you have two options now either create a `jsconfig.json` file in the root of your directory and add this code to it:
```json
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```
Or you can convert the absolute import paths to relative:
```js
import { App } from "components";

/* would become */

import { App } from "./components";
```
Sorry for causing this issue I thought of mentioning it in the post but I assumed people wouldn't be using the same directory structure as me. Don't be worried to ask if you have further questions (either here or directly email me if you like) but for now I'm closing this issue.

**Comment by AngeloGiacco** [comment]
thanks for your help, all sorted!
